# Generated by Django 5.1.3 on 2024-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('left_member', models.IntegerField(blank=True, null=True)),
                ('right_member', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('sale', models.FloatField(blank=True, null=True)),
                ('sponsor_bonus', models.FloatField(blank=True, null=True)),
                ('binary_bonus', models.FloatField(blank=True, null=True)),
                ('left_sales', models.FloatField(blank=True, null=True)),
                ('right_sales', models.FloatField(blank=True, null=True)),
                ('carry_forward', models.FloatField(blank=True, null=True)),
                ('matching_bonus', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
